#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see http://aka.ms/containercompat 

FROM microsoft/dotnet:2.2-aspnetcore-runtime-nanoserver-1803 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk-nanoserver-1803 AS build
WORKDIR /src
COPY src/Catalog.API/Catalog.Api/Catalog.Api.csproj src/Catalog.API/Catalog.Api/
RUN dotnet restore src/Catalog.API/Catalog.Api/Catalog.Api.csproj
COPY . .
WORKDIR /src/src/Catalog.API/Catalog.Api
RUN dotnet build Catalog.Api.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Catalog.Api.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Catalog.Api.dll"]
